name: data-science-binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - plotly
  - statsmodels
  - jupyterlab
  - notebook
  - ipykernel
  - r-base
  - r-mgcv
  - rpy2
  - pip
  - pip:
      - ISLP
